function [x_db, y_db, dx_db_dt, dx_db_de, dy_db_dt, dy_db_de] = koor_dbs(eta,tau)

global xsi_1 xsi_n eta_1 eta_m
global lam_ab lam_bc lam_cd lam_da

f_xsi_n = (xsi_n - tau)./(xsi_n - xsi_1);
f_xsi_1 = (tau - xsi_1)./(xsi_n - xsi_1);
f_eta_m = (eta_m- eta )./(eta_m - eta_1);
f_eta_1 = (eta - eta_1)./(eta_m - eta_1);

eta_anz = 1;
xsi_anz = length(tau);
hb_x = (xd(eta)-xb(eta)) +...
       f_eta_m .* ( (xa(xsi_n)-xa(xsi_1)) -...
       (xsi_n-xsi_1).*(dxadt(xsi_n) - lam_ab.*dybde(eta))) +...
       f_eta_1 .* ( (xc(xsi_n)-xc(xsi_1)) -...
       (xsi_n-xsi_1).*(dxcdt(xsi_n) - lam_bc.*dybde(eta)));
hd_x = (xd(eta)-xb(eta)) +...
       f_eta_m .* ( (xa(xsi_n)-xa(xsi_1)) -...
       (xsi_n-xsi_1).*(dxadt(xsi_1) - lam_da.*dydde(eta))) +...
       f_eta_1 .* ( (xc(xsi_n)-xc(xsi_1)) -...
       (xsi_n-xsi_1).*(dxcdt(xsi_1) - lam_cd.*dydde(eta)));
hb_y = (yd(eta)-yb(eta)) +...
       f_eta_m .* ( (ya(xsi_n)-ya(xsi_1)) -...
       (xsi_n-xsi_1).*(dyadt(xsi_n) + lam_ab.*dxbde(eta))) +...
       f_eta_1 .* ( (yc(xsi_n)-yc(xsi_1)) -...
       (xsi_n-xsi_1).*(dycdt(xsi_n) + lam_bc.*dxbde(eta)));
hd_y = (yd(eta)-yb(eta)) +...
       f_eta_m .* ( (ya(xsi_n)-ya(xsi_1)) -...
       (xsi_n-xsi_1).*(dyadt(xsi_1) + lam_da.*dxdde(eta))) +...
       f_eta_1 .* ( (yc(xsi_n)-yc(xsi_1)) -...
       (xsi_n-xsi_1).*(dycdt(xsi_1) + lam_cd.*dxdde(eta)));

hdb_x = zeros(xsi_anz,eta_anz);
hdb_y = zeros(xsi_anz,eta_anz);

hdb_x = f_xsi_n*xd(eta) + f_xsi_1*xb(eta) +...
        (xa(tau) - f_xsi_n*xa(xsi_1) - f_xsi_1*xa(xsi_n)) * f_eta_m +...
        (xc(tau) - f_xsi_n*xc(xsi_1) - f_xsi_1*xc(xsi_n)) * f_eta_1;
hdb_y = f_xsi_n*yd(eta) + f_xsi_1*yb(eta) +...
        (ya(tau) - f_xsi_n*ya(xsi_1) - f_xsi_1*ya(xsi_n)) * f_eta_m +...
        (yc(tau) - f_xsi_n*yc(xsi_1) - f_xsi_1*yc(xsi_n)) * f_eta_1;

x_db = zeros(xsi_anz,eta_anz);
y_db = zeros(xsi_anz,eta_anz);

x_db  = hdb_x + (f_xsi_1.*(f_xsi_n.^2)) * hd_x -...
                (f_xsi_n.*(f_xsi_1.^2)) * hb_x;
y_db  = hdb_y + (f_xsi_1.*(f_xsi_n.^2)) * hd_y -...
                (f_xsi_n.*(f_xsi_1.^2)) * hb_y;


dhb_x_de = (dxdde(eta)-dxbde(eta)) +...
       f_eta_m .* ( -(xsi_n-xsi_1).*(-lam_ab.*dyb2de2(eta))) -...
       ( (xa(xsi_n)-xa(xsi_1)) - (xsi_n-xsi_1).*(dxadt(xsi_n) - lam_ab.*dybde(eta))) +...
       f_eta_1 .* ( -(xsi_n-xsi_1).*(-lam_bc.*dyb2de2(eta))) +...
       ( (xc(xsi_n)-xc(xsi_1)) - (xsi_n-xsi_1).*(dxcdt(xsi_n) - lam_bc.*dybde(eta)));
dhd_x_de = (dxdde(eta)-dxbde(eta)) +...
       f_eta_m .* ( -(xsi_n-xsi_1).*(-lam_da.*dyd2de2(eta))) -...
       ( (xa(xsi_n)-xa(xsi_1)) - (xsi_n-xsi_1).*(dxadt(xsi_1) - lam_da.*dydde(eta))) +...
       f_eta_1 .* ( -(xsi_n-xsi_1).*(-lam_cd.*dyd2de2(eta))) +...
       ( (xc(xsi_n)-xc(xsi_1)) - (xsi_n-xsi_1).*(dxcdt(xsi_1) - lam_cd.*dydde(eta)));
dhb_y_de = (dydde(eta)-dybde(eta)) +...
       f_eta_m .* ( -(xsi_n-xsi_1).*( lam_ab.*dxb2de2(eta))) -...
       ( (ya(xsi_n)-ya(xsi_1)) - (xsi_n-xsi_1).*(dyadt(xsi_n) + lam_ab.*dxbde(eta))) +...
       f_eta_1 .* ( -(xsi_n-xsi_1).*( lam_bc.*dxb2de2(eta))) +...
       ( (yc(xsi_n)-yc(xsi_1)) - (xsi_n-xsi_1).*(dycdt(xsi_n) + lam_bc.*dxbde(eta)));
dhd_y_de = (dydde(eta)-dybde(eta)) +...
       f_eta_m .* ( -(xsi_n-xsi_1).*( lam_da.*dxd2de2(eta))) -...
       ( (ya(xsi_n)-ya(xsi_1)) - (xsi_n-xsi_1).*(dyadt(xsi_1) + lam_da.*dxdde(eta))) +...
       f_eta_1 .* ( -(xsi_n-xsi_1).*( lam_cd.*dxd2de2(eta))) +...
       ( (yc(xsi_n)-yc(xsi_1)) - (xsi_n-xsi_1).*(dycdt(xsi_1) + lam_cd.*dxdde(eta)));

dhdb_xdt = zeros(xsi_anz,eta_anz);
dhdb_xde = zeros(xsi_anz,eta_anz);
dhdb_ydt = zeros(xsi_anz,eta_anz);
dhdb_yde = zeros(xsi_anz,eta_anz);

dhdb_xdt = ones(size(tau))*(-xd(eta) + xb(eta)) +...
           (dxadt(tau) + xa(xsi_1) - xa(xsi_n)) * f_eta_m +...
           (dxcdt(tau) + xc(xsi_1) - xc(xsi_n)) * f_eta_1;
dhdb_ydt = ones(size(tau))*(-yd(eta) + yb(eta)) +...
           (dyadt(tau) + ya(xsi_1) - ya(xsi_n)) * f_eta_m +...
           (dycdt(tau) + yc(xsi_1) - yc(xsi_n)) * f_eta_1;
dhdb_xde = f_xsi_n*dxdde(eta) + f_xsi_1*dxbde(eta) -...
           (xa(tau) - f_xsi_n*xa(xsi_1) - f_xsi_1*xa(xsi_n)) +...
           (xc(tau) - f_xsi_n*xc(xsi_1) - f_xsi_1*xc(xsi_n));
dhdb_yde = f_xsi_n*dydde(eta) + f_xsi_1*dybde(eta) -...
           (ya(tau) - f_xsi_n*ya(xsi_1) - f_xsi_1*ya(xsi_n)) +...
           (yc(tau) - f_xsi_n*yc(xsi_1) - f_xsi_1*yc(xsi_n));

dx_db_dt = zeros(xsi_anz,eta_anz);
dy_db_dt = zeros(xsi_anz,eta_anz);
dx_db_de = zeros(xsi_anz,eta_anz);
dy_db_de = zeros(xsi_anz,eta_anz);

dx_db_dt  = dhdb_xdt + (f_xsi_n.^2 - 2.*f_xsi_1.*f_xsi_n) * hd_x -...
                       (f_xsi_1.^2 - 2.*f_xsi_1.*f_xsi_n) * hb_x;
dy_db_dt  = dhdb_ydt + (f_xsi_n.^2 - 2.*f_xsi_1.*f_xsi_n) * hd_y -...
                       (f_xsi_1.^2 - 2.*f_xsi_1.*f_xsi_n) * hb_y;
dx_db_de  = dhdb_xde + (f_xsi_1.*(f_xsi_n.^2)) * dhd_x_de -...
                       (f_xsi_n.*(f_xsi_1.^2)) * dhb_x_de;
dy_db_de  = dhdb_yde + (f_xsi_1.*(f_xsi_n.^2)) * dhd_y_de -...
                       (f_xsi_n.*(f_xsi_1.^2)) * dhb_y_de;
